import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex md:flex-row flex-col gap-y-2 gap-x-4 justify-center py-20 mx-auto max-w-2xl">
          <Link
            href="/server-action"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            Server Action
          </Link>
          <Link
            href="/use-action-state"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            useActionState
          </Link>
          <Link
            href="/use-action-state-with-client-validation"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            useActionState With Client Validation
          </Link>
          <Link
            href="/react-hook-form"
            className="text-white underline hover:text-blue-500 transition-colors"
          >
            React Hook Form
          </Link>
        </nav>
        <main className="mx-auto max-w-2xl">{children}</main>
        <Toaster />
      </body>
    </html>
  )
}
